# Generated by Django 4.2.23 on 2025-08-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_booking_no_of_guests_alter_menu_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="no_of_guests",
        ),
        migrations.AddField(
            model_name="booking",
            name="first_name",
            field=models.CharField(default="Existing guests", max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(default="guest"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_slot",
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
