# Generated by Django 4.2.23 on 2025-08-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_remove_booking_booking_date_remove_booking_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="first_name",
            field=models.CharField(max_length=200),
        ),
    ]
